In [2]:
equation  = "1+1/e^-w1x1-w2x2-w3x3"

# TODO : Given any eqation with value of variable,i should get respective derivative to any variable for that equation

In [ ]:
"""parsing the equation"""

In [ ]:
"""calculating the derivative of the equation"""

## simply finding the derivative of sigmoid using flow graph method

In [3]:
import numpy as np

In [53]:
def forward_add(x,y):
    return x+y ,  1, 1

def forward_sum(x):
    return np.sum(x) ,  np.ones_like(x)
def forward_mul(x,y):
    return x*y ,  y, x
def forward_exp(x):
    return np.exp(x) ,  np.exp(x)
def forward_neg(x):
    return -x ,  -1
def forward_inverse(x):
    return 1/x ,  -1/x**2
def forward_sub(x,y):
    return x-y ,  1, -1
def backward_mul(x, y):
    return x*y


In [57]:
w = [2, -3, -3]  # assume random weights and data
x = [-1, -2 ,1]
first_layer = []
for i in range(len(x)):
    first_layer.append(forward_mul(x[i],w[i]))
first_layer=np.array(first_layer)
print(first_layer)

second_layer = forward_sum(first_layer[: ,0 ])
print(second_layer)
third_layer = forward_neg(second_layer[0])
print(third_layer)
fourth_layer = forward_exp(third_layer[0])
print(fourth_layer)
fifth_layer = forward_add(fourth_layer[0],1)
print(fifth_layer)
sixth_layer = forward_inverse(fifth_layer[0])
print(sixth_layer)

[[-2  2 -1]
 [ 6 -3 -2]
 [-3 -3  1]]
(1, array([1, 1, 1]))
(-1, -1)
(0.36787944117144233, 0.36787944117144233)
(1.3678794411714423, 1, 1)
(0.7310585786300049, -0.534446645388523)


In [58]:
ans=backward_mul(sixth_layer[1],fifth_layer[1])
ans=backward_mul(ans ,fourth_layer[1])
ans=backward_mul(ans ,third_layer[1])
ans=backward_mul(ans ,second_layer[1])
final_ans = []
for i in range (len(x)):
    final_ans.append((backward_mul(ans[i] , first_layer[i][1]) , backward_mul(ans[i] , first_layer[i][2])))

In [59]:
final_ans

"""Here first element of the tuple represents the derivative wrt w and second element represents the derivative wrt x"""

[(0.39322386648296376, -0.19661193324148188),
 (-0.5898357997244457, -0.39322386648296376),
 (-0.5898357997244457, 0.19661193324148188)]